name: Build Pyhton App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.90
          
      - name: Install dependancies
        run: pip install -r ./requirements.txt

      - name: Run benchmark
        run: python benchmark.py
