name: Build Pyhton App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.90
          
      - name: Install dependancies
        run: pip install -r ./requirements.txt

      - name: Run benchmark
        run: python main.py

      - name: GIT commit and push all changed files
        env: 
          CI_COMMIT_MESSAGE: Run test
          CI_COMMIT_AUTHOR: Continuous Integration
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add .
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push